config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/new_potin'
  get 'user/:user', to: 'dynamic_pages#user', as: 'user'
  get 'show_potin/:id',  to: 'dynamic_pages#show_potin', as: 'potin'
  get 'dynamic_pages/welcome'
  get 'welcome/:id', to: 'dynamic_pages#welcome', as: 'welcome'
  get 'static_pages/contact'
  get 'static_pages/team'
  get 'home', to: 'static_pages#home'


  post 'static_pages/new_potin' do
    Potin.new(params["gossip_author"], params["gossip_content"]).save
    redirect '/'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/potin.rb
class Potin < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :potins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  def welcome
  end

  def show_potin
    @potin = Potin.find(params[:id])
    @id = params[:id]
  end

  def user
    @user = User.find(params[:user])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @potins = Potin.all
  end

  def team
  end

  def contact
  end

  def new_potin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dynamic_pages/show_potin.html.erb
<br/><h1>Potin n°<%= @potin.id %> : <%= @potin.title %></h1>
  <p><br/>
    <%= "=" * 20 %><br/>
    <%= @potin.description %><br/>
    <%= "=" * 20 %><br/><br/>

    L'auteur : <%= link_to "#{@potin.user.first_name} #{@potin.user.last_name}", user_path(@potin.user.id) %><br>


  </p>

app/views/dynamic_pages/user.html.erb
<br/><h1>Page de <%= @name.first_name %> <%= @user.last_name %></h1>
<p>
  Age : <%= @user.age %><br/>
  Originaire de : <%= @user.origin %>
</p>

app/views/dynamic_pages/welcome.html.erb
<br/><h1>Welcome <%= @name.first_name.capitalize %></h1>
<h5>Ici c'est chez toi.</h5>

  <p>
    Au cas où tu l'aurais oublié, tu as <%= @name.age %> ans<br/>
    Et tu es née à <%= @name.origin %>.
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <header>
    <nav class="navbar navbar-expand navbar-dark bg-primary">
      <%= link_to "Gossips", home_path, :class => "navbar-brand" %>
      <%= link_to "Team", static_pages_team_path, :class => "btn btn-primary my-2 my-sm-0" %>
      <%= link_to "Contact", static_pages_contact_path, :class => "btn btn-primary my-2 my-sm-0" %>
      <%= link_to "Welcome", welcome_path(:name), :class => "btn btn-primary my-2 my-sm-0" %>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Nous contacter</h1>
<p>petit formulaire oklm qui va bien</p>

app/views/static_pages/home.html.erb
<br/><h1>La bienvenue à toi !</h1>
<h5>Tu trouveras la liste des potins ci-dessous et, d'ailleurs, toi aussi tu peux <%= link_to "en ajouter un", static_pages_new_potin_path %> si tu veux ;)</h5><br/>


<% @potins.each do |potin| %>
  <p>
    <%= link_to potin.title, potin_path(potin.id), :class => "btn btn-info my-2 my-sm-0" %><br>
    de <%= potin.user.first_name %>
  </p>
<% end %>

app/views/static_pages/new_potin.html.erb
<br/><h1>Crée un potin !</h1>
<p>Balance ton potin via le formulaire ci-dessous</p>
  <form action='static_pages_new_potin_path' method='POST'>
    Saisi ici ton nom :  <input type='text' name='gossip_author'/><br/>
    Balance ton potin : <input type='text' name='gossip_content'/><br/>
    <input type='submit'/>
  </form>

app/views/static_pages/team.html.erb
<h1>Voici la page Team</h1>
<p>juste pour rappel, le chemin : app/views/static_pages/team.html.erb</p>